### ISSUE TITLE
how to remove or delete item with API?

### ISSUE THREAD

**Issue by nmc79** [hexatester/rosrestpy#2]
Hi
You can guide me how to remove or delete item with your API?
I tried test but error.
>>> test = ros.queue.simple(name="Test")[0]
>>> ros.queue.simple.remove(test.id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Mikrotik\API\rosrestpy-main\ros\_base.py", line 96, in remove
    self.ros.session.delete(self.filename + f"/{self._getid(o)}")
  File "D:\Mikrotik\API\rosrestpy-main\ros\_base.py", line 64, in _getid
    assert hasattr(o, "id"), f"{o} didnt have id from the router"
AssertionError: *1 didnt have id from the router

**Comment by hexatester** [comment]
Just pass the object not the id
```
test = ros.queue.simple(name="Test")[0]
ros.queue.simple.remove(test)
```
